from torch.cuda import is_available

BATCH_SIZE = 32
PATIENCE = 5
STATISTICS_FILE = 'statistics.csv'
USE_CUDA = is_available()
EPOCHS = 10
VERBOSE_LOGGING = False
HIDDEN_SIZE = 100
NUM_EXPERIMENTS = 5
EPSILON = 0.2
DISCOUNT_FACTOR = 0.99
EPSILON_DECAY_FACTOR = 0.99
NUM_EPISODES = 4000
NUM_EPISODES_FOR_DECAY = 100
REPLAY_BATCH_SIZE = 32
REPLAY_CAPACITY = 1000
INITIAL_EPSILON = 1
NUM_STEPS = 5000
NUM_STEPS_FOR_SYNCHRONISING = 100
PRIORITY_ADJUSTMENT_EPSILON = 1e-5
INITIAL_BETA = 0.4
PROBABILITY_POWER = 0.6
ENTROPY_COEFFICIENT = 1e-2
BETA_ADJUSTMENT = 1e-3
PPO_CLIP_FACTOR = 0.2
